[
    { "region": "Quận 1" },
    { "region": "Quận 2" },
    { "region": "Quận 3" },
    { "region": "Quận 4" },
    { "region": "Quận 5" },
    { "region": "Quận 6" },
    { "region": "Quận 7" },
    { "region": "Quận 8" },
    { "region": "Quận 9" },
    { "region": "Quận 10" },
    { "region": "Quận 11" },
    { "region": "Quận 12" },
    { "region": "Thủ Đức" },
    { "region": "Bình Thạnh" },
    { "region": "Bình Tân" },
    { "region": "Tân Bình" },
    { "region": "Tân Phú" },
    { "region": "Hóc Môn" }
]